# -*- coding: utf-8 -*-
"""UPGRADE PROJECT DAY 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACfRsEZctBJjrDV_P97LLna65ULBJtiI
"""

num = int(input("Enter a number : "))
if num<=1:
  print(num, "is not a prime number")
else:
  for i in range(2,num):
     if(num%i)==0:
        print(num, "is not a prime number")
        break
  else:
      print(num, " is a prime number")

num = int(input("Enter a number : "))
if num<=1:
  print("NOT PRIME")
else:
  for i in range(2,num):
    if(num%i)==0:
      print("NOT PRIME")
      break
  else:
        print("PRIME")







